# Generated by Django 3.1.2 on 2022-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toTitle', models.CharField(default='New Todo', max_length=120)),
                ('toDesc', models.TextField(blank=True, default='')),
            ],
        ),
    ]
